spring.application.name=nail-service
spring.datasource.url=jdbc:postgresql://localhost:5433/nail_db
spring.datasource.username=postgres
spring.datasource.password=2208

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true